FROM ubuntu:24.04
WORKDIR /build
RUN apt update && apt install -y \
    gcc \
    build-essential \
    make \
    libpcre3-dev \
    libssl-dev \
    zlib1g-dev \
    ccache \
    lcov \
    bc \
    && rm -rf /var/lib/apt/lists/*
